--- #YAML:1.0
name:               App-Skate
version:            0.044
abstract:           Cat with syntax highlighting powers
author:
    - Magnus Woldrich <trapd00r@trapd00r.se>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Syntax::Highlight::Engine::Kate:  0
    Term::ExtendedColor:  0
resources:
    bugtracker:  https://github.com/trapd00r/Skate/issues
    repository:  https://github.com/trapd00r/Skate
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
